### ISSUE TITLE
Notice: Undefined property: stdClass::$language in _entity_token_wrap_data()

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/entity_token#4]
Module entity_token should update to the actual langcode property.

There are some occurrences of `$options['language']->language` which should get updated to `->langcode`.

**Comment by argiepiano** [comment]
Fixed in #14 . Thank you, @Wylbur  !  And thank you @indigoxela for reporting.

Please notice that this issue has also been solved in version 2.x of Entity Tokens, which will become the default version of the module very soon, and will depend on entity_plus 1.0.14. Version 2 solves this and several other issues and collisions with core tokens.
